drop table if exists users cascade;
drop table if exists items cascade;
drop table if exists tags cascade;

create table users
(
    id                int generated by default as identity primary key,
    first_name        varchar(30),
    last_name         varchar(50),
    email             varchar(100),
    registration_date timestamp,
    state             varchar(8)
);

create table items
(
    id            int generated by default as identity primary key,
    name          varchar(100),
    user_id       int references users,
    url           varchar(200),
    resolved_url  varchar,
    mime_type     varchar,
    title         varchar,
    has_image     boolean,
    has_video     boolean,
    date_resolved timestamp,
    unread boolean
);

create table tags
(
    id      int generated by default as identity primary key,
    name    varchar(100),
    item_id int references items
);